#!/bin/bash
sudo yum install docker -y
sudo systemctl start docker
sudo docker pull hariharansdeveloper/aws_trial:latest
sudo docker run -d -p 3000:3000 --name aws_trial-container hariharansdeveloper/aws_trial


# sudo docker ps